name: Python Lint & Security

on:
  workflow_call:
    inputs:
      enable-black:
        type: string
        default: "true"

      enable-flake8:
        type: string
        default: "true"

      enable-isort:
        type: string
        default: "true"

      enable-bandit:
        type: string
        default: "true"

      enable-ruff:
        type: string
        default: "false"

      enable-flake8-nb:
        type: string
        default: "false"

jobs:
  lint:
    name: Lint / Style / Security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: black
        if: inputs.enable-black == 'true'
        run: |
          pip install "black>=25"
          black --check .

      - name: flake8_nb
        if: inputs.enable-flake8-nb == 'true'
        run: |
          pip install flake8_nb
          flake8_nb

      - name: flake8 + pep8-naming
        if: inputs.enable-flake8 == 'true'
        run: |
          pip install flake8 pep8-naming
          flake8

      - name: isort
        if: inputs.enable-isort == 'true'
        run: |
          pip install isort
          isort --check-only .

      - name: ruff
        if: inputs.enable-ruff == 'true'
        run: |
          pip install ruff
          ruff check .

      - name: bandit
        if: inputs.enable-bandit == 'true'
        run: |
          pip install "bandit[toml]"
          bandit -c pyproject.toml -r .
