name: Python Publish

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        type: string
        default: "3.12"

jobs:
  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Twine
        run: python -m pip install twine

      - name: Publish to TestPyPI
        run: python -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: "__token__"

  publish-pypi:
    name: Publish to PyPI
    needs: publish-testpypi
    runs-on: ubuntu-latest
    environment: publish-pypi   # requires human approval
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Twine
        run: python -m pip install twine

      - name: Publish to PyPI
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"

  tag-release:
    name: Tag Release
    needs: publish-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package
        run: pip install dist/*.tar.gz

      - name: Get distribution name (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $DISTRO_NAME = "${env:GITHUB_REPOSITORY_NAME}" -replace "-", "_"
          echo "DISTRO_NAME=$DISTRO_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Get distribution name (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          DISTRO_NAME="${GITHUB_REPOSITORY//-/_}"
          echo "DISTRO_NAME=${DISTRO_NAME}" >> $GITHUB_ENV

      - name: Get package version
        shell: bash
        run: |
          TAG_VERSION=$(python -c 'from importlib.metadata import version; import os; print(version(os.environ["DISTRO_NAME"]))')
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
          echo "Detected version: ${TAG_VERSION}"

      - name: Create Git tag
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          API_URL="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/git/refs"
          API_VERSION="2022-11-28"
          TAG_NAME="v${TAG_VERSION}"
          REF_SHA="${GITHUB_SHA}"
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -L --request POST \
            --url "${API_URL}" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}" \
            --header "Content-Type: application/json" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: ${API_VERSION}" \
            --data "{
              \"ref\": \"refs/tags/${TAG_NAME}\",
              \"sha\": \"${REF_SHA}\"
            }")
          if [[ "$RESPONSE" -ne 201 ]]; then
            echo "‚ùå GitHub API request failed with status code: $RESPONSE"
            cat response.json
            exit 1
          fi
