name: Python Documentation

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version for documentation build"
        type: string
        default: "3.12"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-python-package@main
        with:
          python-version: ${{ inputs.python-version }}
          install-extras: "doc"

      - name: Build documentation
        run: sphinx-build ./doc ./html
